# Generated by Django 5.1.3 on 2025-01-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='content',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='is_master',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='title',
        ),
        migrations.AddField(
            model_name='resume',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='contact_email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_experience',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='applied', max_length=20),
        ),
    ]
