# Generated by Django 5.1.3 on 2025-01-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_resume_contact_email_alter_resume_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='contact_email',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projects',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='resume',
            name='work_experience',
            field=models.JSONField(default=list),
        ),
    ]
